import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Blog Posts from Api",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </head>
          <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-20 min-h-screen h-screen flex flex-col   `}
      >

    <nav className={"text-center   fixed top-0 left-0 w-full"} >
      <div className="container ">

      <ul className='    p-5 flex justify-around  uppercase nav-style'>
      <li className='nav-active  '><Link href="/"> Blog News</Link></li>
      <li className=''><Link href="#"> Lifestyle</Link></li>
        <li><Link href="#" > entertainment</Link></li>
         <li><Link href="#" > world</Link></li>
          <li><Link href="#" > sport</Link></li>
          <li><Link href="#" > travel</Link></li>
           <li><Link href="#" > technology</Link></li>
      </ul>
      </div>
    </nav>
     <main className="wrapper flex-auto ">
        {children}

     </main>

            <footer className=' text-center'>

      <div className="container  py-5">
        <p> All rights Reserved &copy;</p>
      </div>
     </footer>
      </body>
    </html>
  );
}
